# -*- coding: utf-8 -*-
"""TensorFlowTutorial.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KnCnskqnKOkYtsq3K15C2ZcpGGcTcxG1

# **Load Dataset into Model**
"""

import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt
print(tf.__version__)
fashion_mnist = tf.keras.datasets.fashion_mnist
(training_images, training_labels), (test_images, test_labels) = fashion_mnist.load_data()
class_names = ['T-shirt/top', 'Trouser', 'Pullover', 'Dress', 'Coat', 'Sandal', 'Shirt', 'Sneaker', 'Bag', 'Ankle boot']
training_images.shape
model = tf.keras.Sequential([
tf.keras.layers.Flatten(input_shape=(28, 28)),
tf.keras.layers.Dense(128, activation='relu'),
tf.keras.layers.Dense(10)
])

"""# **Training Model**"""

model.compile(
optimizer='adam',
loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),
metrics=['accuracy']
)
model.fit(training_images, training_labels, epochs=10)
model.evaluate(test_images, test_labels) #[Loss, Accuracy] Goal: Loss decrease and Accuracy increases

"""# **Predict Model**"""

probability_model = tf.keras.Sequential([model, tf.keras.layers.Softmax()])
predictions = probability_model.predict(test_images)
predictions[0]
plt.bar(class_names, predictions[0])
plt.xlabel('Categories')
plt.ylabel('Prediction Probability')
plt.title('Prediction Probabilities Bar Graph')
plt.xticks(rotation=45, ha='right') # Rotate labels
plt.tight_layout() # Adjust layout
plt.show()
plt.figure()
plt.imshow(test_images[0])
plt.colorbar()
plt.grid(False)
plt.show()